export const getContacts = (state) => state.contacts;
export const getFilter = (state) => state.filter;
export const getToken = (state) => state.token;
export const getUser = (state) => state.user;
export const isAuthentificated = (state) => state.authentificated;
export const isLoadingApp = (state) => state.loader.loaderApp;
export const isLoadingButton = (state) => state.loader.loaderButton;
export const isLoadingContacts = (state) => state.loader.loaderContacts;
export const getAuthError = (state) => state.authError;
